spring:
  application:
    name: dataCenter
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/data_center?serverTimezone=Asia/Shanghai
    username: root
    password: root
    initial-size: 1
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat

dao:
  mybatis:
    plus:
      config:
        global:
          id-type: 0
          db-type: mysql
          db-column-underline: true
          logic-delete-value: 0
          logic-not-delete-value: 0
        sql:
          session:
            factory:
              mapper-locations: classpath:mybatis/mapper/aieqMapper.xml
              configLocation: classpath:mybatis/mybatis-context.xml
              type-aliases-package: com.gougu.dao..model
    config:
      mapper:
        scanner:
          sql-session-factory-bean-name: sqlSessionFactory

server:
  port: 8889

#  日志配置
logging:
  level:
    root: info
    age com.gougu: debug




